### PR TITLE
Handling admins users, updating docker and python dependencies & small display fixes

### PR DESCRIPTION
**Pull request by carsso**

### CODE REVIEW

**Comment by adamcharnock** [comment]
Thanks for this @carsso! This all looks great to me, merging now.

**Comment by carsso** [comment]
😉 Thanks.
Could you build the updated docker image on docker hub ?

I tried the automatic build from my fork repo here https://hub.docker.com/r/carsso/factorio-status-ui and it works like a charm. Now the PR is merged, you should be able to do it as well 🙂.

**Comment by carsso** [comment]
@adamcharnock 
😉 Thanks.
Could you build the updated docker image on docker hub ?

I tried the automatic build from my fork repo here https://hub.docker.com/r/carsso/factorio-status-ui and it works like a charm. Now the PR is merged, you should be able to do it as well 🙂.

**Comment by adamcharnock** [comment]
Ah yes. I've just pushed a new `latest` build to docker hub.

**Comment by carsso** [comment]
Thanks :)

**Pull request merged**
